---
title: "week3-lab"
format: html
---

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)
library(tidyr)
library(ggplot2)

#..........................import data...........................
#drought <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-07-20/drought.csv')

drought <- readr::read_csv(here::here("week3", "data", "dm_export_20000101_20260121.csv"))
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>
  
  # Pivot table to be in tidy form
  pivot_longer(cols = None:D4, names_to = "drought_lvl",    values_to = "area_pct") |>
  
  janitor::clean_names() |>
  
  # Rename state abbreviation column
   rename(state_abb = state_abbreviation) |>

  # select cols of interest & update names for clarity (as needed) ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year, month & day cols using {lubridate} fxns ----
  # NOTE: this step isn't necessary for our plot, but I'm including as examples of how to extract different date elements from a object of class `Date` using {lubridate} ----
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("(D4) Exceptional", "(D3) Extreme",
                                       "(D2) Severe", "(D1) Moderate", 
                                       "(D0) Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  relocate(date, year, month, day, state_abb, drought_lvl, drought_lvl_long, area_pct)
```


```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
custom_palette <- c("#FFFF05", "#FFE79A", "#FFC201", "#FF0000", "#853A04")

#date = seq(as.Date("2023-01-01"), as.Date("2023-12-31"), by = "month")
#drought_clean$date <- year(drought_clean$date)



drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") %>% 

  
  # pipe into ggplot here!
  ggplot() + 
  geom_area(aes(x = date, #factor(year), 
                y = area_pct, 
                group = drought_lvl, 
                fill = drought_lvl)) + 
  scale_fill_manual(values = custom_palette, 
                    labels = c("D0 (Abnormally Dry)", "D1 (Moderate)", "D2 (Severe)", "D3 (Extreme)", "D4 (Exceptional)")) + 
  #scale_x_discrete(breaks = seq(2000, 2026,by = 2)) +
  scale_x_date(breaks = scales::breaks_pretty(20), 
               expand = c(0,0) 
               #minor_breaks =scales::breaks_pretty()
               ) + 
  scale_y_continuous(labels = scales::label_percent(scale = 1), 
                     breaks = seq(0, 100, by = 10),
                     expand = c(0,0)) + 
  theme_bw() +
  theme(axis.title = element_blank(), # remove x and y axis 
        legend.position = "bottom",  # legend to bottom 
        plot.title = element_text(hjust = 0.5), # title to middle 
        plot.margin = margin(t =15, r = 15, b = 15, l = 15),# Add margin around plot 
        legend.title = element_blank()) + # remove legend name 
  labs(title = "Drought area in California")


```

